// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: chitchat.proto

package chitchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN EventType = 0
	EventType_EVENT_TYPE_CHAT    EventType = 1
	EventType_EVENT_TYPE_JOIN    EventType = 2
	EventType_EVENT_TYPE_LEAVE   EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNKNOWN",
		1: "EVENT_TYPE_CHAT",
		2: "EVENT_TYPE_JOIN",
		3: "EVENT_TYPE_LEAVE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNKNOWN": 0,
		"EVENT_TYPE_CHAT":    1,
		"EVENT_TYPE_JOIN":    2,
		"EVENT_TYPE_LEAVE":   3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chitchat_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_chitchat_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{0}
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=EventType" json:"type,omitempty"`
	ClientId      int32                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LamportTime   int64                  `protobuf:"varint,4,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_chitchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (x *ChatEvent) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ChatEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatEvent) GetLamportTime() int64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_chitchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LamportTime   int64                  `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_chitchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *JoinResponse) GetLamportTime() int64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_chitchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_chitchat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{4}
}

func (x *PublishResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_chitchat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_chitchat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_chitchat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chitchat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{8}
}

var File_chitchat_proto protoreflect.FileDescriptor

const file_chitchat_proto_rawDesc = "" +
	"\n" +
	"\x0echitchat.proto\"\x99\x01\n" +
	"\tChatEvent\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".EventTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x05R\bclientId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\flamport_time\x18\x04 \x01(\x03R\vlamportTime\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\".\n" +
	"\vJoinRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\"N\n" +
	"\fJoinResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x03R\vlamportTime\"G\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"#\n" +
	"\x0fPublishResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"+\n" +
	"\fLeaveRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\"!\n" +
	"\rLeaveResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\",\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\"\a\n" +
	"\x05Empty*c\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fEVENT_TYPE_CHAT\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_JOIN\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_LEAVE\x10\x032\xc0\x01\n" +
	"\x0fChitChatService\x12#\n" +
	"\x04Join\x12\f.JoinRequest\x1a\r.JoinResponse\x120\n" +
	"\vSendMessage\x12\x0f.PublishRequest\x1a\x10.PublishResponse\x12&\n" +
	"\x05Leave\x12\r.LeaveRequest\x1a\x0e.LeaveResponse\x12.\n" +
	"\x0eStreamMessages\x12\x0e.StreamRequest\x1a\n" +
	".ChatEvent0\x01B Z\x1eChitChatPractice/grpc/chitchatb\x06proto3"

var (
	file_chitchat_proto_rawDescOnce sync.Once
	file_chitchat_proto_rawDescData []byte
)

func file_chitchat_proto_rawDescGZIP() []byte {
	file_chitchat_proto_rawDescOnce.Do(func() {
		file_chitchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chitchat_proto_rawDesc), len(file_chitchat_proto_rawDesc)))
	})
	return file_chitchat_proto_rawDescData
}

var file_chitchat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chitchat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chitchat_proto_goTypes = []any{
	(EventType)(0),          // 0: EventType
	(*ChatEvent)(nil),       // 1: ChatEvent
	(*JoinRequest)(nil),     // 2: JoinRequest
	(*JoinResponse)(nil),    // 3: JoinResponse
	(*PublishRequest)(nil),  // 4: PublishRequest
	(*PublishResponse)(nil), // 5: PublishResponse
	(*LeaveRequest)(nil),    // 6: LeaveRequest
	(*LeaveResponse)(nil),   // 7: LeaveResponse
	(*StreamRequest)(nil),   // 8: StreamRequest
	(*Empty)(nil),           // 9: Empty
}
var file_chitchat_proto_depIdxs = []int32{
	0, // 0: ChatEvent.type:type_name -> EventType
	2, // 1: ChitChatService.Join:input_type -> JoinRequest
	4, // 2: ChitChatService.SendMessage:input_type -> PublishRequest
	6, // 3: ChitChatService.Leave:input_type -> LeaveRequest
	8, // 4: ChitChatService.StreamMessages:input_type -> StreamRequest
	3, // 5: ChitChatService.Join:output_type -> JoinResponse
	5, // 6: ChitChatService.SendMessage:output_type -> PublishResponse
	7, // 7: ChitChatService.Leave:output_type -> LeaveResponse
	1, // 8: ChitChatService.StreamMessages:output_type -> ChatEvent
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chitchat_proto_init() }
func file_chitchat_proto_init() {
	if File_chitchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chitchat_proto_rawDesc), len(file_chitchat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chitchat_proto_goTypes,
		DependencyIndexes: file_chitchat_proto_depIdxs,
		EnumInfos:         file_chitchat_proto_enumTypes,
		MessageInfos:      file_chitchat_proto_msgTypes,
	}.Build()
	File_chitchat_proto = out.File
	file_chitchat_proto_goTypes = nil
	file_chitchat_proto_depIdxs = nil
}
